apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nfs-server-provisioner-0
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
