apiVersion: v1
kind: Namespace
metadata:
  name: nfs-server

---
apiVersion: v1
kind: Pod
metadata:
  name: jupyterhub-nfs
  namespace: nfs-server
spec:
  containers:
  - name: nfs-server
    image: gcr.io/google-samples/nfs-server:1.1
    ports:
      - name: nfs
        containerPort: 2049
      - name: mountd
        containerPort: 20048
      - name: rpcbind
        containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /exports
        name: mypvc
  volumes:
  - name: mypvc
    hostPath:
      path: /home/openthings/data

---
kind: Service
apiVersion: v1
metadata:
  name: jupyterhub-nfs
  namespace: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: jupyterhub-nfs
