apiVersion: 0.1.0
environments:
  kubeflow013:
    destination:
      namespace: kubeflow013
      server: https://192.168.199.249:6443
    k8sVersion: v1.10.2
    path: kubeflow013
  nocloud:
    destination:
      namespace: kubeflow-dev
      server: https://192.168.199.249:6443
    k8sVersion: v1.10.2
    path: nocloud
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 665db361bf33405e3bba78b77d9d339421e9cd78
      refSpec: v0.1.3
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 665db361bf33405e3bba78b77d9d339421e9cd78
      refSpec: v0.1.3
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 665db361bf33405e3bba78b77d9d339421e9cd78
      refSpec: v0.1.3
    name: tf-serving
    registry: kubeflow
name: kubeflow013
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 665db361bf33405e3bba78b77d9d339421e9cd78
      refSpec: v0.1.3
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.1.3/kubeflow
version: 0.0.1
