apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "stolon.keeper.fullname" . }}
  labels:
    app: {{ template "stolon.keeper.fullname" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "stolon-keeper"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "stolon.keeper.fullname" . }}
  replicas: {{ .Values.keeper.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "stolon.keeper.fullname" . }}
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "stolon-keeper"
        stolon-cluster: {{ template "stolon.clusterName" . }}
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10

{{- if .Values.keeper.affinity }}
      affinity:
{{ toYaml .Values.keeper.affinity | indent 8 }}
{{- end }}

{{- if .Values.keeper.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.keeper.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.keeper.tolerations }}
      tolerations:
{{ toYaml .Values.keeper.tolerations | indent 8 }}
{{- end }}

      containers:
      - name: {{ template "stolon.keeper.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            # Generate our keeper uid using the pod index
            IFS='-' read -ra ADDR <<< "$(hostname)"
            export STKEEPER_UID="keeper${ADDR[-1]}"
            export POD_IP=$(hostname -i)
            export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
            export STOLON_DATA=/stolon-data
            chown stolon:stolon $STOLON_DATA
            exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STKEEPER_CLUSTER_NAME
            value: {{ template "stolon.clusterName" . }}
          - name: STKEEPER_STORE_BACKEND
            value: {{ .Values.store.backend  | quote}}
          {{- if eq .Values.store.backend "kubernetes" }}
          - name: STKEEPER_KUBE_RESOURCE_KIND
            value: {{ default "configmap" .Values.store.kubeResourceKind  | quote}}
          {{- else }}
          - name: STKEEPER_STORE_ENDPOINTS
            value: {{ .Values.store.endpoints | quote}}
          {{- end }}
          - name: STKEEPER_PG_REPL_USERNAME
            value: {{ .Values.pgReplUsername  | quote}}
          - name: STKEEPER_PG_REPL_PASSWORDFILE
            value: "/etc/secrets/stolon/pg_repl_password"
          - name: STKEEPER_PG_SU_USERNAME
            value: {{ .Values.pgSuperuserName  | quote}}
          - name: STKEEPER_PG_SU_PASSWORDFILE
            value: "/etc/secrets/stolon/pg_su_password"
          - name: STKEEPER_DEBUG
            value: {{ .Values.debug | quote}}
        ports:
          - containerPort: {{ .Values.ports.internalPort }}
        volumeMounts:
        - name: stolon-data
          mountPath: /stolon-data
        - name: stolon-secrets
          mountPath: /etc/secrets/stolon
        resources:
{{ toYaml .Values.keeper.resources | indent 10 }}
      volumes:
        - name: stolon-secrets
          secret:
            secretName: {{ template "stolon.fullname" . }}

{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: stolon-data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
    {{- else }}
        storageClassName: default
  {{- end }}
{{- else }}
        - name: stolon-data
          emptyDir: {}
{{- end }}
