apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "stolon.sentinel.fullname" . }}
  labels:
    app: {{ template "stolon.sentinel.fullname" . }}
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "stolon-sentinel"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.sentinel.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "stolon.sentinel.fullname" . }}
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "stolon-sentinel"
        stolon-cluster: {{ template "stolon.clusterName" . }}
        stolon-sentinel: "true"
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
{{- if .Values.sentinel.affinity }}
      affinity:
{{ toYaml .Values.sentinel.affinity | indent 8 }}
{{- end }}

{{- if .Values.sentinel.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentinel.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.sentinel.tolerations }}
      tolerations:
{{ toYaml .Values.sentinel.tolerations | indent 8 }}
{{- end }}

      containers:
      - name: {{ template "stolon.sentinel.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STSENTINEL_CLUSTER_NAME
            value: {{ template "stolon.clusterName" .}}
          - name: STSENTINEL_STORE_BACKEND
            value: {{ .Values.store.backend | quote}}
          {{- if eq .Values.store.backend "kubernetes" }}
          - name: STSENTINEL_KUBE_RESOURCE_KIND
            value: {{ default "configmap" .Values.store.kubeResourceKind  | quote}}
          {{- else }}
          - name: STSENTINEL_STORE_ENDPOINTS
            value: {{ .Values.store.endpoints | quote}}
          {{- end }}
          - name: STSENTINEL_DEBUG
            value: {{ .Values.debug | quote}}
        resources:
{{ toYaml .Values.sentinel.resources | indent 10 }}
