{
 "title": "Kubernetes Capacity",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CPU Cores Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode=\"idle\"}[2m])) * 100 / count(node_cpu{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance))",
     "legendFormat": "Requested CPU Cores"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "load 1m" },
    { "expr": "sum(node_load5)", "legendFormat": "load 5m" },
    { "expr": "sum(node_load15)", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_memory_bytes) by (instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested Memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)",
     "legendFormat": "memory usage"
    },
    { "expr": "sum(node_memory_Buffers)", "legendFormat": "memory buffers" },
    { "expr": "sum(node_memory_Cached)", "legendFormat": "memory cached" },
    { "expr": "sum(node_memory_MemFree)", "legendFormat": "memory free" }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_bytes_read[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_ms[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "Current number of Pods" },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "Maximum capacity of pods"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{device!~\"lo\"}[5m]))"
    }
   ]
  }
 ]
}