docker pull jupyterhub/k8s-hub:36a8dcb
docker pull jupyterhub/configurable-http-proxy:3.0.0
docker pull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
docker pull jetstack/kube-lego:0.1.6
docker pull jupyterhub/k8s-network-tools:36a8dcb
docker pull jupyterhub/k8s-singleuser-sample:36a8dcb
docker pull jupyterhub/k8s-image-awaiter:36a8dcb
docker pull gcr.io/google_containers/pause:3.0
docker pull jupyterhub/k8s-pod-culler:36a8dcb
